version: "3.3"

services:
  app:
    container_name: app
    build: .
    command: bash -c "cd app && /usr/local/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000    
    restart: always
